### ISSUE TITLE
interpolate_missing_periods {quitte} docu mismatch

### ISSUE THREAD

**Issue by rauner** [pik-piam/quitte#14]
interpolate_missing_periods {quitte} "periods" in docu but expects "period"

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
`periods` is the parameter to the standard evaluation version `interpolate_missing_periods_()`, listing which periods should be interpolated (e.g. `2005`, `2010`, …) and how they are named in the data frame `data` (e.g. `period`, `year`, …).
`period` is the name of the temporal dimension in `quitte` data frames, and as such the default value if no name is given.  But any name is possible.

```R
(data <- tibble(
    group  = rep(c('A', 'B'), c(8, 4)),
    item   = c(rep('x', 4), rep('y', 4), rep('x', 4)),
    year   = rep(c(2015, 2025, 2030, 2035), 3),
    value  = c(2, 4, 5, 6, 20, NA, 50, 60, NA, 400, 500, NA)))

interpolate_missing_periods(data, year = c(2015, 2020, 2025, 2030, 2035))
```
