### ISSUE TITLE
[Feature request] fast way to read subset of variables into quitte df 

### ISSUE THREAD

**Issue by bs538** [pik-piam/quitte#17]
Would it be possible to have a function to read only a subset of variables from one or multiple mif/csv files into a quitte dataframe? To make it fast, the best way is probably to pre-filter the file(s) using command line tools behind the scenes, and then to read only the filtered temporary file? (as suggested in previous discussions on Mattermost)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Have a link to a couple of example .mif files that I can use for profiling?

**Comment by bs538** [comment]
Sure, lots of coupled mifs here: /p/projects/piam/SDP_runs/SDP_round1/remind/output/C_*.mif

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> […] using command line tools behind the scenes […]

creates dependencies of those tools.  And I don't want to deal with support demands from Windows users ;)

So I did the next best thing: speed up `read.quitte()` (14dfebd).

Wall-time for
```
read.quitte(list.files('/p/projects/piam/SDP_runs/SDP_round1/remind/output/', 
                       '^C.*mif$', full.names = TRUE))
```
changed from eight minutes to 22 seconds.
