### ISSUE TITLE
warning from replace_column with ambigous mask

### ISSUE THREAD

**Issue by rkrekeler** [pik-piam/quitte#21]
`replace_column` works silently even if provided with an ambiguous mask that maps values to multiple other values (i.e. columns of mask contain duplicates). In all my applications so far, this would be a mistake and the result with more rows than `data` was not what I intended calculate.
Do you think it makes sense to give a warning or even throw an error if this kind of `mask` is not explicitly allowed via a new argument? Or are my use cases just a very limited fraction of what this function should be able to do?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Do you have a minimal working example?

**Comment by rkrekeler** [comment]
Sure: 
````R
model_data <- data.frame(
    model  = c('Model1', '2ndModel', 'Model Three'),
    region = c('Region 1', 'Region 2', 'Region 1'),
    value  = 1:3)
mask <- data.frame(
    model  = c('Model1', '2ndModel', 'Model Three', 'Model Three'),
    clear_name = paste('Model', 1:4))
replace_column(model_data, mask, model, clear_name)
    model   region value
1 Model 1 Region 1     1
2 Model 2 Region 2     2
3 Model 3 Region 1     3
4 Model 4 Region 1     3
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I did a warning, not an error, so as to not break any existing code. 291b162

**Comment by rkrekeler** [comment]
> I did a warning, not an error, so as to not break any existing code. [291b162](https://github.com/pik-piam/quitte/commit/291b1623a05d517e1f94f257f0235785c744680e)

Makes sense. Thank you!
