### ISSUE TITLE
Too much filling by completeMissing in calc_addVariable?

### ISSUE THREAD

**Issue by rkrekeler** [pik-piam/quitte#22]
I am still struggling with `calc_addVariable` if `completeMissing == TRUE` (related to [this comment](https://github.com/pik-piam/quitte/issues/18#issuecomment-929875828)). The function will fill much more "missing data combinations" with zero than I expected.
``` R
> data
  model variable period value
1    m1        A      1     1
2    m1        A      2     2
3    m1        A      3     3
4    m1        B      1     4
5    m1        B      2     5
6    m2        A      1     6
7    m2        A      2     7
8    m2        B      1     8
9    m2        B      2     9
> calc_addVariable(data, C = "A + B", completeMissing = TRUE)
   model variable period value
 1 m1    A             1     1
 2 m1    B             1     4
 3 m1    C             1     5
 4 m1    A             2     2
 5 m1    B             2     5
 6 m1    C             2     7
 7 m1    A             3     3
 8 m1    B             3     0
 9 m1    C             3     3
10 m2    A             1     6
11 m2    B             1     8
12 m2    C             1    14
13 m2    A             2     7
14 m2    B             2     9
15 m2    C             2    16
16 m2    A             3     0
17 m2    B             3     0
18 m2    C             3     0
```
In the case above, I don't see the need to fill values for period 3 in model m2 because none of the variables A and B are defined for this combination. So I would expect the result without rows 16-18. Row 8 on the other hand should be filled in order to calculate row 9.
If the current behavior should remain, is it possible to introduce an reduced version of the argument like `completeGaps` that would only fill missing variables for data combination that exist for at least one of the variable used in the calculation?
I might have a special use case, but in EDGE-Buildings we often have the scenario history with values for historic periods and the scenarios SSP* for projected periods. `calc_addVariable` with `completeMissing == TRUE` introduces many unwanted zeros.
I can imagine this to require a bit more effort. So if there is no time for this feature (or my suggestion makes no sense at all), this issues is just to flag the behaviour I described. Thanks in any case!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> I don't see the need to fill values for period 3 in model m2

Inferring what the user sees to need is a rather complicated matter …

You would need to tell `calc_addVariable()` which combinations of columns you do care about, at which point the syntax will get quite involved, to the point the option isn't used anymore since nobody knows what it is doing.

I would suggest to be more verbose in your code, getting rid of you unwanted combinations after calculations like so:
```R
d %>% 
    calc_addVariable(C = 'A + B', completeMissing = TRUE) %>% 
    semi_join(
        d %>% 
            distinct(variable, period),
        
        c('variable', 'period')
    )
```

**Comment by rkrekeler** [comment]
Cool, thank you.
