### ISSUE TITLE
default handling of Inf in read.quitte

### ISSUE THREAD

**Issue by chroetz** [pik-piam/quitte#33]
Currently `read.quitte("scenario.mif")` throws a (non-helpful) warning if the mif file contains `Inf` or `-Inf` as values. This can be prevented by adding `"Inf", "-Inf"` to the argument `na.strings`, e.g., `read.quitte("scenario.mif", na.strings = c("UNDF", "NA", "N/A", "n_a", "Inf", "-Inf"))`. It would be nice if either this would be the default or if `"Inf"` would be correctly parsed as the value `Inf`.

**Comment by chroetz** [comment]
A change in read.quitte, potentially requires or suggests changes here:
* https://github.com/chroetz/remind2/blob/49adaa55a9ca48727ac708be1877c6625f0cf282/inst/markdown/compareScenarios2/cs2_main.Rmd#L139

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I will extend the warning to make it clear that `readr::problems()` is meant (pik-piam/quitte#34).
And the `Inf` entries in the .mif files are neither "undefined", nor "not applicable", but actually an error in REMIND post-processing (pik-piam/remind2#132).  I can't think of a scenario where REMIND would need to legitimately report an `Inf` value.  Maybe some elasticity, but we neither report them nor are we using infinite elasticities at the moment.
So no on the suggested change.
