### ISSUE TITLE
quitte::read.quitte() return object not recognized by tidyr::pivot_wider() as tibble

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/quitte#4]
Hey Michaja, 

so Silvia and I happened upon this little bug/anomaly: 
**When reading in a mif file with `read.quitte()`, the returned object is not recognized by `pivot_wider()` as a tibble. Even though `is_tibble()` returns TRUE, you have to pass the quitte object through `as_tibble()`, before `pivot_wider()` accepts it.**

Below is some code describing the problem. Specifically a warning message that is only displayed every 8 hours(?). Does the problem maybe have something to do with the use of the deprecated `data_frame()` function?

So I was wondering if this is something you were aware of and if it needs fixing. I am glad to work on it, I just wanted to get your input on this. 

Thanks a lot!

```
x<- read.quitte("output/default_2020-03-03_09.38.01/REMIND_generic_default.mif")
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

```
x
A tibble: 356,649 x 7
model  scenario region variable    unit               period value
   <fct>  <fct>    <fct>  <fct>       <fct>               <int> <dbl>
 1 REMIND default  CAZ    Consumption billion US$2005/yr   2005  972.
 2 REMIND default  CHA    Consumption billion US$2005/yr   2005 3493.
 3 REMIND default  EUR    Consumption billion US$2005/yr   2005 7846.
 4 REMIND default  IND    Consumption billion US$2005/yr   2005  898.
 5 REMIND default  JPN    Consumption billion US$2005/yr   2005 2671.
 6 REMIND default  LAM    Consumption billion US$2005/yr   2005 1710.
 7 REMIND default  MEA    Consumption billion US$2005/yr   2005 1086.
 8 REMIND default  NEU    Consumption billion US$2005/yr   2005  858.
 9 REMIND default  OAS    Consumption billion US$2005/yr   2005 1402.
10 REMIND default  REF    Consumption billion US$2005/yr   2005  660.
… with 356,639 more rows
```

```
x %>%  pivot_wider(names_from = variable)
Error: `x` must be a vector, not a `tbl_df/tbl/data.frame/quitte` object.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
1. Why are you shouting? Or is there any point to the all bold-face paragraph? ;)

2. 
    >`data_frame()` is deprecated as of tibble 1.1.0.
    > Please use `tibble()` instead.

    That will eliminate the warning and will make `quitte` not break once they kick `data_frame()` out, 
    but it won't change the behaviour, since `data_frame()` calls `tibble()` internally.

3. Did some light digging.  The problem is that `vctrs::vec_unique_loc()` does not like any extra classes on the objects.  So it's either calling `as_tibble()` to drop the `quitte` class (won't be a quitte afterwards anyhow), or taking it up with the folks at [the vctrs package](https://github.com/r-lib/vctrs).

**Comment by johanneskoch94** [comment]
Okok, thanks for the explanation!
(I wanted to highlight ;) I'll leave it out next time sry.)
